name: migrationbench
channels:
  - conda-forge
dependencies:
  - python=3.11
  - ase=3.25.0
  - matplotlib=3.9.4
  - numpy=2.0.2
  - pandas=2.3.1
  - pytest=8.4.2
  - pyyaml=6.0.2
  - scikit-learn=1.6.1
  - scipy=1.13.1
  - pyarrow=17.0.0
  - snakemake=8.25.5
  - pip
  - pip:
      - mace-torch==0.3.12
      - snakemake-executor-plugin-slurm==0.13.0
